<a href="https://colab.research.google.com/github/fatoufall737/atelier-pandas-iot/blob/main/atelier_pandas_iot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contexte
Une entreprise possède plusieurs bâtiments équipés de capteurs IoT.
Chaque capteur collecte régulièrement des informations sur la température, l'humidité, la pression,
la consommation énergétique, l'état du capteur, le bâtiment, la date et l'heure de la mesure.
Les données doivent être préparées et analysées avant d'être transmises à un futur système de
Machine Learning permettant de détecter des situations anormales.
Structure du projet
1) Structurer le projet comme suit :
atelier_pandas_iot/
│
├── data/
│   
├── mesures_capteurs.csv
│    
├── notebooks/
│   
└── atelier_pandas_iot.ipynb
│
└── exports/
├── donnees_nettoyees.csv
└── donnees_nettoyees.json
2) Stocker le fichier fourni mesures_capteurs.csv dans le sous-dossier data
3) Créer le notebook atelier_pandas_iot.ipynb
NB : les fichiers du sous-dossier exports seront créés à la fin de l’atelier

Partie 1 – Series
1) Créer une Series contenant 4 températures  
2) Afficher son index
3) Afficher la 1ère valeur
4) Afficher la dernière valeur
5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de
mesure 12h, 13h, 14h et 15h
6) Afficher la 1ère et la dernière valeur

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 1) Créer une Series contenant 4 températures
temperatures_series = pd.Series([24.5, 25.1, 26.3, 27.0])
temperatures_series

0    24.5
1    25.1
2    26.3
3    27.0
dtype: float64

In [ ]:
# 2) Afficher son index
temperatures_series.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
# 3) Afficher la 1ère valeur
temperatures_series[0]

np.float64(24.5)

In [ ]:
# 4) Afficher la dernière valeur
temperatures_series.iloc[-1]

np.float64(27.0)

In [ ]:
# 5) Series avec index personnalisé (heures), deux méthodes

# Méthode 1 : en passant le paramètre index directement
temperatures_horaires_v1 = pd.Series([24.5, 25.1, 26.3, 27.0], index=["12h", "13h", "14h", "15h"])
temperatures_horaires_v1

12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [ ]:
# Méthode 2 : en créant d'abord la Series par défaut, puis en modifiant .index
temperatures_horaires_v2 = pd.Series([24.5, 25.1, 26.3, 27.0])
temperatures_horaires_v2.index = ["12h", "13h", "14h", "15h"]
temperatures_horaires_v2

12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [ ]:
# 6) Afficher la 1ère et la dernière valeur
print("1ère valeur   :", temperatures_horaires_v1.iloc[0])
print("Dernière valeur:", temperatures_horaires_v1.iloc[-1])

1ère valeur   : 24.5
Dernière valeur: 27.0

Partie 2 – DataFrame
1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant
data = {
"capteur": ["C001", "C002", "C003"],
"temperature": [24.5, 25.1, 26.3],
"humidite": [65, 67, 70]
}
2) Importer le dataset mesures_capteurs.csv dans le dataframe df
3) Afficher les dimensions de df
NB : dans la suite de l’atelier, on travaillera avec le dataframe df

In [ ]:
# 1) Créer et afficher le dataframe df_test à partir du dictionnaire
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

In [ ]:
# 2) Importer le dataset mesures_capteurs.csv dans le dataframe df
from google.colab import files
uploaded = files.upload()  # sélectionne mesures_capteurs.csv depuis ton ordinateur

Saving mesures_capteurs.csv to mesures_capteurs.csv

In [ ]:
df = pd.read_csv("mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [ ]:
# 3) Afficher les dimensions de df
df.shape

(605, 9)

Partie 3 – Exploration
1) Afficher les premières lignes
2) Afficher les 10 premières lignes
3) Afficher les dernières lignes
4) Afficher le nombre de lignes
5) Afficher le nombre de colonnes
6) Afficher les noms des colonnes
7) Afficher les informations générales
8) Afficher les statistiques descriptives

In [ ]:
# 1) Afficher les premières lignes
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [ ]:
# 2) Afficher les 10 premières lignes
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

In [ ]:
# 3) Afficher les dernières lignes
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [ ]:
# 4) Afficher le nombre de lignes
df.shape[0]

605

In [ ]:
# 5) Afficher le nombre de colonnes
df.shape[1]

9

In [ ]:
# 6) Afficher les noms des colonnes
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='object')

In [ ]:
# 7) Afficher les informations générales
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB

In [ ]:
# 8) Afficher les statistiques descriptives
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

Partie 4 – Sélection  
1) Sélectionner la colonne "temperature"
2) Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"  
3) Sélectionner les 5 premières lignes avec loc
4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

In [ ]:
# 1) Sélectionner la colonne "temperature"
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

In [ ]:
# 2) Sélectionner plusieurs colonnes
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

In [ ]:
# 3) Sélectionner les 5 premières lignes avec loc
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [ ]:
# 4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

Partie 5 – Manipulation des colonnes
1) Ajouter la colonne "temperature_fahrenheit"
2) Ajouter la colonne "niveau_temperature"
 pour catégoriser la température en  
"Élevée" (température > 30) ou "Normale". On peut utiliser la méthode where() de numpy
3) Renommer la colonne "humidite" en "humidite_relative"
4) Supprimer la colonne "temperature_fahrenheit"

In [ ]:
# 1) Ajouter la colonne "temperature_fahrenheit"
df["temperature_fahrenheit"] = df["temperature"] * 9/5 + 32
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,temperature_fahrenheit
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044

In [ ]:
# 2) Ajouter la colonne "niveau_temperature" (catégorisation avec np.where)
df["niveau_temperature"] = np.where(df["temperature"] > 30, "Élevée", "Normale")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044,Normale

In [ ]:
# 3) Renommer la colonne "humidite" en "humidite_relative"
df = df.rename(columns={"humidite": "humidite_relative"})
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044,Normale

In [ ]:
# 4) Supprimer la colonne "temperature_fahrenheit"
df = df.drop(columns=["temperature_fahrenheit"])
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,Normale

Partie 6 – Filtrage
1) Récupérer uniquement les lignes telles que température
 > 30
2) Récupérer uniquement les lignes telles température
 > 30 et humidité > 70

In [ ]:
# 1) Lignes où température > 30
df_temp_sup_30 = df[df["temperature"] > 30]
df_temp_sup_30

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
63,M0064,2026-01-07 15:00:00,C004,B002,31.19,55.13,1011.04,264.98,OK,Élevée
79,M0275,2026-01-16 10:00:00,C011,B004,31.74,69.95,1020.79,335.89,OK,Élevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Élevée
103,M0311,2026-01-17 22:00:00,C011,B004,30.83,54.99,1026.47,256.11,OK,Élevée
112,M0149,2026-01-11 04:00:00,C005,B002,31.46,48.48,1002.75,210.94,OK,Élevée
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
137,M0076,2026-01-08 03:00:00,C004,B002,31.18,49.66,1019.91,215.22,OK,Élevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Élevée
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK,Élevée
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Élevée
174,M0405,2026-01-21 20:00:00,C009,B003,31.74,47.23,1015.59,115.79,OK,Élevée
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Élevée
243,M0416,2026-01-22 07:00:00,C008,B003,30.16,54.00,1012.18,875.00,ERREUR,Élevée
246,M0312,2026-01-17 23:00:00,C012,B004,30.13,65.68,1009.70,198.65,OK,Élevée
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE,Élevée
257,M0378,2026-01-20 17:00:00,C006,B002,31.99,66.32,1013.54,254.67,OK,Élevée
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK,Élevée
274,M0046,2026-01-06 21:00:00,C010,B004,30.92,67.19,1009.71,329.78,OK,Élevée
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK,Élevée
322,M0120,2026-01-09 23:00:00,C012,B004,30.19,53.58,1013.05,396.90,ALERTE,Élevée
356,M0574,2026-01-28 21:00:00,C010,B004,30.61,60.73,1022.32,321.75,OK,Élevée
362,M0396,2026-01-21 11:00:00,C012,B004,30.57,63.47,1017.40,248.36,OK,Élevée
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK,Élevée
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE,Élevée
401,M0586,2026-01-29 09:00:00,C010,B004,31.44,63.10,996.56,271.51,OK,Élevée
404,M0598,2026-01-29 21:00:00,C010,B004,30.37,64.55,997.31,311.77,OK,Élevée
417,M0432,2026-01-22 23:00:00,C012,B004,30.38,65.98,1005.48,256.18,OK,Élevée
437,M0286,2026-01-16 21:00:00,C010,B004,32.16,41.80,996.99,255.56,ALERTE,Élevée
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Élevée
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Élevée
488,M0431,2026-01-22 22:00:00,C011,B004,30.14,51.02,1007.70,366.53,ALERTE,Élevée
492,M0552,2026-01-27 23:00:00,C012,B004,30.24,62.06,1009.35,299.69,OK,Élevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Élevée
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
505,M0268,2026-01-16 03:00:00,C004,B002,30.34,64.23,1011.42,179.84,OK,Élevée
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK,Élevée
558,M0346,2026-01-19 09:00:00,C010,B004,30.68,36.33,1010.46,272.59,OK,Élevée

In [ ]:
# 2) Lignes où température > 30 ET humidité > 70
df_filtre = df[(df["temperature"] > 30) & (df["humidite_relative"] > 70)]
df_filtre

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
88,M0288,2026-01-16 23:00:00,C012,B004,30.06,75.30,1014.47,323.32,OK,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
145,M0503,2026-01-25 22:00:00,C011,B004,30.57,71.26,1002.88,359.97,OK,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
168,M0276,2026-01-16 11:00:00,C012,B004,30.39,71.14,1017.79,303.38,OK,Élevée
210,M0588,2026-01-29 11:00:00,C012,B004,31.51,72.49,1018.21,307.97,OK,Élevée
251,M0114,2026-01-09 17:00:00,C006,B002,31.85,85.77,1013.56,237.21,ALERTE,Élevée
264,M0191,2026-01-12 22:00:00,C011,B004,30.75,71.35,1018.92,308.66,OK,Élevée
280,M0585,2026-01-29 08:00:00,C009,B003,31.30,73.35,1021.40,187.98,OK,Élevée
385,M0126,2026-01-10 05:00:00,C006,B002,30.09,73.95,1007.24,162.39,OK,Élevée
398,M0514,2026-01-26 09:00:00,C010,B004,30.48,93.57,1015.93,306.24,ALERTE,Élevée
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
541,M0202,2026-01-13 09:00:00,C010,B004,30.86,76.00,1011.94,224.01,OK,Élevée

Partie 7 : Tri
1) Créer df_trie1 pour trier en fonction de la température croissante
2) Créer df_trie2 pour trier en fonction de la température décroissante
3) Créer top10 pour voir les 10 températures les plus élevées
4) Trier en fonction des colonnes "batiment" (croissant) et "temperature" (décroissant)

In [31]:
# 1) Tri par température croissante
df_trie1 = df.sort_values(by="temperature")
df_trie1.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
487,M0538,2026-01-27 09:00:00,C010,B004,-18.50,66.27,1012.49,312.92,ERREUR,Normale
245,M0127,2026-01-10 06:00:00,C007,B003,14.11,145.00,1032.36,169.57,ERREUR,Normale
258,M0223,2026-01-14 06:00:00,C007,B003,15.49,47.96,1006.34,124.90,OK,Normale
249,M0175,2026-01-12 06:00:00,C007,B003,16.04,55.36,1005.68,140.95,OK,Normale
59,M0146,2026-01-11 01:00:00,C002,B001,16.77,53.44,1010.65,131.75,OK,Normale

In [32]:
# 2) Tri par température décroissante
df_trie2 = df.sort_values(by="temperature", ascending=False)
df_trie2.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée

In [33]:
# 3) Top 10 des températures les plus élevées
top10 = df.sort_values(by="temperature", ascending=False).head(10)
top10

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
502,M0048,2026-01-06 23:00:00,C012,B004,58.70,81.51,1026.79,271.92,ERREUR,Élevée
43,M0575,2026-01-28 22:00:00,C011,B004,34.72,57.50,1008.94,266.22,ALERTE,Élevée
129,M0592,2026-01-29 15:00:00,C004,B002,33.60,79.80,1021.96,212.55,ALERTE,Élevée
211,M0370,2026-01-20 09:00:00,C010,B004,33.29,50.43,1009.87,356.76,ALERTE,Élevée
165,M0323,2026-01-18 10:00:00,C011,B004,33.01,73.24,1014.36,260.24,ALERTE,Élevée
118,M0365,2026-01-20 04:00:00,C005,B002,32.90,65.91,1027.28,246.08,ALERTE,Élevée
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
438,M0558,2026-01-28 05:00:00,C006,B002,32.56,67.77,1016.88,181.51,ALERTE,Élevée
47,M0082,2026-01-08 09:00:00,C010,B004,32.46,72.31,1000.42,276.99,ALERTE,Élevée
169,M0546,2026-01-27 17:00:00,C006,B002,32.36,67.34,998.10,184.89,ALERTE,Élevée

In [34]:
# 4) Tri multi-colonnes : batiment croissant, temperature décroissant
df_trie_multi = df.sort_values(by=["batiment", "temperature"], ascending=[True, False])
df_trie_multi.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
520,M0063,2026-01-07 14:00:00,C003,B001,32.72,53.28,1010.05,195.37,ALERTE,Élevée
447,M0170,2026-01-12 01:00:00,C002,B001,31.15,69.20,1016.10,172.49,OK,Élevée
224,M0303,2026-01-17 14:00:00,C003,B001,30.84,67.98,1020.09,157.99,OK,Élevée
500,M0062,2026-01-07 13:00:00,C002,B001,30.39,52.13,1004.23,262.66,OK,Élevée
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK,Normale
467,M0241,2026-01-15 00:00:00,C001,B001,28.85,66.31,1004.98,175.06,OK,Normale
567,M0591,2026-01-29 14:00:00,C003,B001,28.71,55.02,1010.18,201.62,OK,Normale
85,M0074,2026-01-08 01:00:00,C002,B001,28.41,39.33,1011.11,187.94,OK,Normale
293,M0230,2026-01-14 13:00:00,C002,B001,28.31,70.29,1023.91,95.36,OK,Normale
263,M0579,2026-01-29 02:00:00,C003,B001,28.11,65.56,1016.97,196.48,OK,Normale

Partie 8 : Analyse
1) Afficher la consommation moyenne par bâtiment
2) Afficher le minimum, le maximum, la moyenne et l’écart-type de la température par bâtiment
3) Afficher, par bâtiment, le maximum et la moyenne de la température et de la consommation
4) Afficher la température moyenne globale
5) Afficher la température maximale
6) Afficher la consommation totale
7) Quel bâtiment consomme le plus en moyenne ?
8) Afficher le nombre d'alertes par bâtiment

In [35]:
# 1) Consommation moyenne par bâtiment
df.groupby("batiment")["consommation"].mean()

batiment
B001    177.870927
B002    221.785333
B003    153.191000
B004    282.552282
Name: consommation, dtype: float64

In [36]:
# 2) Min, max, moyenne, écart-type de la température par bâtiment
df.groupby("batiment")["temperature"].agg(["min", "max", "mean", "std"])

            min    max       mean       std
batiment
B001      16.77  32.72  23.578824  2.961211
B002      17.67  33.60  25.778000  2.951828
B003      14.11  31.74  23.013699  2.983902
B004     -18.50  58.70  27.119000  5.367361

In [37]:
# 3) Max et moyenne de température et consommation, par bâtiment
df.groupby("batiment")[["temperature", "consommation"]].agg(["max", "mean"])

         temperature            consommation
                 max       mean          max        mean
batiment
B001           32.72  23.578824       294.72  177.870927
B002           33.60  25.778000       335.20  221.785333
B003           31.74  23.013699       875.00  153.191000
B004           58.70  27.119000       411.12  282.552282

In [38]:
# 4) Température moyenne globale
df["temperature"].mean()

np.float64(24.87831385642738)

In [39]:
# 5) Température maximale
df["temperature"].max()

58.7

In [40]:
# 6) Consommation totale
df["consommation"].sum()

np.float64(125205.25)

In [41]:
# 7) Bâtiment qui consomme le plus en moyenne
df.groupby("batiment")["consommation"].mean().idxmax()

'B004'

In [42]:
# 8) Nombre d'alertes par bâtiment
df[df["etat"] == "ALERTE"].groupby("batiment").size()

batiment
B001     2
B002     7
B003     5
B004    15
dtype: int64

Partie 9 : Gestion des valeurs manquantes
1) Afficher le nombre de valeurs manquantes par colonne
2) Afficher le nombre total des valeurs manquantes
3) Afficher le taux de valeurs manquantes
4) Afficher les lignes contenant des valeurs manquantes
5) Pour la température et l’humidité, remplacer les valeurs manquantes par les moyennes
6) Pour la consommation, remplacer les valeurs manquantes par la médiane

In [43]:
# 1) Nombre de valeurs manquantes par colonne
df.isnull().sum()

id_mesure             0
date_heure            0
id_capteur            0
batiment              0
temperature           6
humidite_relative     5
pression              5
consommation          5
etat                  4
niveau_temperature    0
dtype: int64

In [44]:
# 2) Nombre total de valeurs manquantes
df.isnull().sum().sum()

np.int64(25)

In [45]:
# 3) Taux de valeurs manquantes
taux_manquant = df.isnull().sum().sum() / df.size * 100
taux_manquant

np.float64(0.4132231404958678)

In [46]:
# 4) Lignes contenant des valeurs manquantes
df[df.isnull().any(axis=1)]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
14,M0056,2026-01-07 07:00:00,C008,B003,22.33,67.42,1014.41,101.20,NaN,Normale
30,M0073,2026-01-08 00:00:00,C001,B001,23.12,63.97,NaN,186.87,OK,Normale
91,M0473,2026-01-24 16:00:00,C005,B002,21.32,70.43,1021.20,194.76,NaN,Normale
128,M0300,2026-01-17 11:00:00,C012,B004,23.32,55.73,NaN,232.38,OK,Normale
139,M0345,2026-01-19 08:00:00,C009,B003,NaN,66.77,1015.33,216.31,OK,Normale
146,M0118,2026-01-09 21:00:00,C010,B004,30.32,NaN,1015.78,261.68,OK,Élevée
149,M0034,2026-01-06 09:00:00,C010,B004,28.91,NaN,1001.23,234.30,OK,Normale
163,M0019,2026-01-05 18:00:00,C007,B003,NaN,69.97,1014.14,181.07,OK,Normale
196,M0372,2026-01-20 11:00:00,C012,B004,29.33,56.91,1020.02,NaN,OK,Normale
215,M0204,2026-01-13 11:00:00,C012,B004,NaN,59.96,1007.98,294.02,OK,Normale
270,M0334,2026-01-18 21:00:00,C010,B004,29.63,67.70,1016.30,363.68,NaN,Normale
303,M0584,2026-01-29 07:00:00,C008,B003,23.78,64.66,NaN,153.81,OK,Normale
307,M0169,2026-01-12 00:00:00,C001,B001,21.86,51.83,NaN,195.72,OK,Normale
323,M0391,2026-01-21 06:00:00,C007,B003,21.82,NaN,1006.47,98.39,OK,Normale
459,M0143,2026-01-10 22:00:00,C011,B004,28.65,66.88,1001.41,NaN,OK,Normale
476,M0527,2026-01-26 22:00:00,C011,B004,26.16,NaN,1024.21,232.87,OK,Normale
490,M0227,2026-01-14 10:00:00,C011,B004,25.13,85.60,1011.20,NaN,ALERTE,Normale
491,M0449,2026-01-23 16:00:00,C005,B002,26.82,61.99,NaN,215.34,OK,Normale
511,M0506,2026-01-26 01:00:00,C002,B001,24.04,57.10,1014.04,NaN,OK,Normale
513,M0490,2026-01-25 09:00:00,C010,B004,NaN,52.97,1010.71,253.63,OK,Normale
526,M0015,2026-01-05 14:00:00,C003,B001,23.17,79.95,1006.07,NaN,OK,Normale
536,M0252,2026-01-15 11:00:00,C012,B004,27.01,NaN,1018.36,263.13,OK,Normale
548,M0572,2026-01-28 19:00:00,C008,B003,NaN,68.63,1018.58,252.48,OK,Normale
556,M0092,2026-01-08 19:00:00,C008,B003,NaN,79.81,1007.05,113.00,OK,Normale
572,M0190,2026-01-12 21:00:00,C010,B004,24.24,73.55,1018.12,299.91,NaN,Normale

In [48]:
# 5) Remplacer les valeurs manquantes de température et humidité par la moyenne
df["temperature"] = df["temperature"].fillna(df["temperature"].mean())
df["humidite_relative"] = df["humidite_relative"].fillna(df["humidite_relative"].mean())

In [49]:
# 6) Remplacer les valeurs manquantes de consommation par la médiane
df["consommation"] = df["consommation"].fillna(df["consommation"].median())

In [50]:
# 7) Remplacer les valeurs manquantes de "etat" par "INCONNU"
df["etat"] = df["etat"].fillna("INCONNU")