<a href="https://colab.research.google.com/github/fatoufall737/atelier-pandas-iot/blob/main/atelier_pandas_iot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Contexte
Une entreprise possède plusieurs bâtiments équipés de capteurs IoT.
Chaque capteur collecte régulièrement des informations sur la température, l'humidité, la pression,
la consommation énergétique, l'état du capteur, le bâtiment, la date et l'heure de la mesure.
Les données doivent être préparées et analysées avant d'être transmises à un futur système de
Machine Learning permettant de détecter des situations anormales.
Structure du projet
1) Structurer le projet comme suit :
atelier_pandas_iot/
│
├── data/
│   
├── mesures_capteurs.csv
│    
├── notebooks/
│   
└── atelier_pandas_iot.ipynb
│
└── exports/
├── donnees_nettoyees.csv
└── donnees_nettoyees.json
2) Stocker le fichier fourni mesures_capteurs.csv dans le sous-dossier data
3) Créer le notebook atelier_pandas_iot.ipynb
NB : les fichiers du sous-dossier exports seront créés à la fin de l’atelier

Partie 1 – Series
1) Créer une Series contenant 4 températures  
2) Afficher son index
3) Afficher la 1ère valeur
4) Afficher la dernière valeur
5) Créer, de deux façon différentes, une Series de 4 températures avec comme index les heures de
mesure 12h, 13h, 14h et 15h
6) Afficher la 1ère et la dernière valeur

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1) Créer une Series contenant 4 températures
temperatures_series = pd.Series([24.5, 25.1, 26.3, 27.0])
temperatures_series

0    24.5
1    25.1
2    26.3
3    27.0
dtype: float64

In [3]:
# 2) Afficher son index
temperatures_series.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
# 3) Afficher la 1ère valeur
temperatures_series[0]

np.float64(24.5)

In [5]:
# 4) Afficher la dernière valeur
temperatures_series.iloc[-1]

np.float64(27.0)

In [6]:
# 5) Series avec index personnalisé (heures), deux méthodes

# Méthode 1 : en passant le paramètre index directement
temperatures_horaires_v1 = pd.Series([24.5, 25.1, 26.3, 27.0], index=["12h", "13h", "14h", "15h"])
temperatures_horaires_v1

12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [7]:
# Méthode 2 : en créant d'abord la Series par défaut, puis en modifiant .index
temperatures_horaires_v2 = pd.Series([24.5, 25.1, 26.3, 27.0])
temperatures_horaires_v2.index = ["12h", "13h", "14h", "15h"]
temperatures_horaires_v2

12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

In [8]:
# 6) Afficher la 1ère et la dernière valeur
print("1ère valeur   :", temperatures_horaires_v1.iloc[0])
print("Dernière valeur:", temperatures_horaires_v1.iloc[-1])

1ère valeur   : 24.5
Dernière valeur: 27.0

Partie 2 – DataFrame
1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant
data = {
"capteur": ["C001", "C002", "C003"],
"temperature": [24.5, 25.1, 26.3],
"humidite": [65, 67, 70]
}
2) Importer le dataset mesures_capteurs.csv dans le dataframe df
3) Afficher les dimensions de df
NB : dans la suite de l’atelier, on travaillera avec le dataframe df

In [9]:
# 1) Créer et afficher le dataframe df_test à partir du dictionnaire
data = {
    "capteur": ["C001", "C002", "C003"],
    "temperature": [24.5, 25.1, 26.3],
    "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

In [10]:
# 2) Importer le dataset mesures_capteurs.csv dans le dataframe df
from google.colab import files
uploaded = files.upload()  # sélectionne mesures_capteurs.csv depuis ton ordinateur

Saving mesures_capteurs.csv to mesures_capteurs.csv

In [11]:
df = pd.read_csv("mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [12]:
# 3) Afficher les dimensions de df
df.shape

(605, 9)

Partie 3 – Exploration
1) Afficher les premières lignes
2) Afficher les 10 premières lignes
3) Afficher les dernières lignes
4) Afficher le nombre de lignes
5) Afficher le nombre de colonnes
6) Afficher les noms des colonnes
7) Afficher les informations générales
8) Afficher les statistiques descriptives

In [13]:
# 1) Afficher les premières lignes
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [14]:
# 2) Afficher les 10 premières lignes
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

In [15]:
# 3) Afficher les dernières lignes
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

In [16]:
# 4) Afficher le nombre de lignes
df.shape[0]

605

In [17]:
# 5) Afficher le nombre de colonnes
df.shape[1]

9

In [18]:
# 6) Afficher les noms des colonnes
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='object')

In [19]:
# 7) Afficher les informations générales
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    object
 1   date_heure    605 non-null    object
 2   id_capteur    605 non-null    object
 3   batiment      605 non-null    object
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    object
dtypes: float64(4), object(5)
memory usage: 42.7+ KB

In [20]:
# 8) Afficher les statistiques descriptives
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

Partie 4 – Sélection  
1) Sélectionner la colonne "temperature"
2) Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"  
3) Sélectionner les 5 premières lignes avec loc
4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc

In [21]:
# 1) Sélectionner la colonne "temperature"
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

In [22]:
# 2) Sélectionner plusieurs colonnes
df[["temperature", "humidite", "pression", "consommation"]]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

In [23]:
# 3) Sélectionner les 5 premières lignes avec loc
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

In [24]:
# 4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001

Partie 5 – Manipulation des colonnes
1) Ajouter la colonne "temperature_fahrenheit"
2) Ajouter la colonne "niveau_temperature" pour catégoriser la température en  
"Élevée" (température
 > 30) ou "Normale". On peut utiliser la méthode where() de numpy
3) Renommer la colonne "humidite" en "humidite_relative"
4) Supprimer la colonne "temperature_fahrenheit"

In [25]:
# 1) Ajouter la colonne "temperature_fahrenheit"
df["temperature_fahrenheit"] = df["temperature"] * 9/5 + 32
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,temperature_fahrenheit
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044

In [26]:
# 2) Ajouter la colonne "niveau_temperature" (catégorisation avec np.where)
df["niveau_temperature"] = np.where(df["temperature"] > 30, "Élevée", "Normale")
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044,Normale

In [27]:
# 3) Renommer la colonne "humidite" en "humidite_relative"
df = df.rename(columns={"humidite": "humidite_relative"})
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,temperature_fahrenheit,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,77.828,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,75.200,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,78.476,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,82.814,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,69.044,Normale

In [28]:
# 4) Supprimer la colonne "temperature_fahrenheit"
df = df.drop(columns=["temperature_fahrenheit"])
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite_relative,pression,consommation,etat,niveau_temperature
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK,Normale
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK,Normale
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK,Normale
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK,Normale
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK,Normale